# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558af55d99fc0982bccae65227c0a3a695ed07ede402b474aff68a2e4fc8aa35a65e0317d827924bf905c955167006d266b737b7d5b1bc3709eef1823baae7d7

test:
  secret_key_base: 05075dffbcf53f2176b3b2755afd5b59e614cc56a08c167df52b740b17f350cd5b0888b2760e52bb4f0350fa7573cb83f7ce88320c432ab74c134119234ab43e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
